### ISSUE TITLE
How to uninstall open cas ?

### ISSUE THREAD

**Issue by ck332864** [Open-CAS/open-cas-linux#102]
I was trying opencas on rhel 7.6. I would like to build an rpm with the list of cas related binaries, configuration files. Unfortunately , I was not able to find the list of files to put them all together.Below are the list of files I was able to find:
$) ll /sbin/cas*
-rwxr-xr-x 1 root root 192112 Sep 16 14:19 /sbin/casadm
lrwxrwxrwx 1 root root     19 Sep 16 14:19 /sbin/casctl -> /lib/opencas/casctl
$) ll /lib/opencas/
total 40
-rwxr-xr-x 1 root root  4651 Sep 16 14:19 casctl
-rwxr-xr-x 1 root root  1736 Sep 16 14:19 open-cas-loader
-rwxr-xr-x 1 root root   815 Sep 16 14:19 open-cas-mount-utility
-rw-r--r-- 1 root root 23408 Sep 16 14:19 opencas.py

**Comment by kiransgithub** [comment]
I think $make uninstall command might work for deleting the installed files.

One more observation: With ./configure its not accepting --prefix to provide a installation directory or path.

**Comment by robertbaldyga** [comment]
@ck332864 Here you have complete list of files installed by `make install`:
```
/lib/modules/4.4.0-28-generic/extra/cas_disk.ko
/lib/modules/4.4.0-28-generic/extra/cas_cache.ko
/sbin/casadm
/usr/share/man/man8/casadm.8
/etc/opencas/opencas.conf
/etc/opencas/ioclass-config.csv
/etc/opencas/ext3-config.csv
/etc/opencas/ext4-config.csv
/usr/share/man/man5/opencas.conf.5
/lib/opencas/opencas.py
/lib/opencas/casctl
/lib/opencas/open-cas-loader
/lib/opencas/open-cas-mount-utility
/lib/udev/rules.d/60-persistent-storage-cas-load.rules
/lib/udev/rules.d/60-persistent-storage-cas.rules
/usr/share/man/man8/casctl.8
/lib/systemd/system/open-cas-shutdown.service
/lib/systemd/system/../system-shutdown/open-cas.shutdown
```
As @kiransgithub said, you can remove all these files with `make uninstall` command.

**Comment by robertbaldyga** [comment]
@kiransgithub It's because this is not typical autoconf `configure`. The `configure` script generates header file needed to compile Open CAS modules against specific kernel. That's right, we have abstracted out all differences between wide range of kernel versions and generate header with these abstractions wrappers for each kernel version separately. This way we are able to have common code base compiling on many different kernels, including custom kernels which have partially backported functionality.
