### ISSUE TITLE
[21.6.4] test_ioclass_id_as_condition: Writes were not properly cached

### ISSUE THREAD

**Issue by karolinavelkaja** [Open-CAS/open-cas-linux#1046]
## Description

test_ioclass_id_as_condition: Writes were not properly cached

**Failing case for ext4 filesystem**

## Steps to Reproduce

1. Prepare cache and core. Disable udev.
2. Create and load IO class config file.
3. Prepare ext4 filesystem and mount /dev/cas1-1 at /tmp/cas1-1.
4. Run IO fulfilling IO class 1 condition (and not IO class 2) and check if it is classified properly.
    fio --eta=always --output-format=json --output=fio_run_2022-01-15_03-51-1642215115 --ioengine=libaio --size=1048576 --readwrite=write --filename=/tmp/cas1-1/base_dir/test_file_1 --name=fio --group_reporting
    **Failed: Writes were not properly cached!
    Expected: 1048576.0 Byte, actual: 0.0 Blocks4096**

## Logs

[2022_01_15_03_50_18_test_ioclass_id_as_condition.zip](https://github.com/Open-CAS/open-cas-linux/files/7889516/2022_01_15_03_50_18_test_ioclass_id_as_condition.zip)

## Your Environment

* OpenCAS version (commit hash or tag): 21.6.4
* Operating System: Rhel 8.4

**Comment by jfckm** [comment]
The defect is caused by CAS not being able to resolve directory to inode so quickly.

Here is where it's defined in code:
https://github.com/Open-CAS/open-cas-linux/blob/7041517bf47df08b75aa4727189dc612ee8d4bc6/modules/cas_cache/classifier.c#L318-L328

As you can see CAS resolves directory by means of delayed work, which is run periodically (1s for not-yet-resolved directories, 5s for resolved). In this particular test the window between creating directory and running workload is so small that most of the times CAS doesn't have the time to resolve inode number.

Although adding slight (1s) delay before running fio is not pretty it should do the job.

**Comment by karolinavelkaja** [comment]
Confirming that adding the delay resolves the issue and test is passing

**Comment by karolinavelkaja** [comment]
Test fix needed, expected behavior from CAS perspective.

**Comment by karolinavelkaja** [comment]
Test improvement implemented, closing.
