### ISSUE TITLE
Checksums do not match - OpenCAS Linux master on 5.18 kernel

### ISSUE THREAD

**Issue by Kgierszx** [Open-CAS/open-cas-linux#1408]
## Description

Checksums of /dev/cas1-1 and an underlying device do not match after flush when running WB mode on latest master on 5.18 kernel.

## Expected Behavior

Checksums should match (i.e. data should be identical) on both /dev/cas1-1 and an underlying device.

## Actual Behavior

Checksums do not match after issuing a flush.

## Steps to Reproduce

1. Start cache in WB mode 
2. Set NOP cleaning policy and sequential cutoff threshold of 0
3. Add core
4. Fill cache with data
5. Issue cache flush (casadm -F)
6. Get md5sum of /dev/cas1-1 and an underlying core device (e.g. /dev/sdc)

## Your Environment

* OpenCAS version (commit hash or tag): master, d0bfa9485360899563bfbd1bb3ff3cb4025ee9db
* Operating System: Ubuntu 22.04
* Kernel version: 5.18.19
* Cache device type (NAND/Optane/other):
* Core device type (HDD/SSD/other):
* Cache configuration:
* * Cache mode: WB
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: NOP
* * Sequential cutoff policy: 0
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by Kgierszx** [comment]
CentOS on kernel 5.15 md5sums are matched. However, on Ubuntu 22.04 LTS with stock 5.15 kernel md5sums do not match. On Ubuntu 20.04 with stock 4.15 kernel md5sums are matched. Manual execution of steps test_parallel_core_flushing.

**Comment by kmajzero** [comment]
Confirmed - the issue exists on Ubuntu 22.04 LTS with stock 5.15 and 5.18.19-generic kernels - the md5 sums do not match after flush-cache command. They match only after stopping the cache. 

However, on Arch Linux with linux-lts 5.15.77-lts kernel, the issue is NOT observable - flush-cache command works as expected.
On Arch Linux with stock 6.0.7 kernel, the issue IS observable - again, md5sums match only after stopping the cache.

The issue is not observable on CentOS 8 with 5.15 (custom) kernel - md5 sums are matching after issuing a flush cache command.

**Comment by kmajzero** [comment]
After much analysis, this issue is a test error. OpenCAS does not support getting data from an underlying core device while the cache is active and running. The cache must be stopped whenever an underlying core block device is to be accessed.
