### ISSUE TITLE
Issue 253 is not resolved yet

### ISSUE THREAD

**Issue by beef9999** [Open-CAS/open-cas-linux#311]
https://github.com/Open-CAS/open-cas-linux/issues/253

Got metadata corrupted after system reboot.

**Comment by mmichal10** [comment]
@beef9999 

According to logs you attached in #253 it is no longer issue with data corruption.

My guess is that you created cache instance with older version of open cas linux. Since then our internal metadata structures might have changed and simple cache load is not possible. Try to create fresh instance of cache (with OCL containing commit 9653b76a) and then try to execute your test.
Please let me know if everything was ok. 

Few more words about updating OCL to newer version with having cache instances running.
We are preparing feature called upgrade in flight - it temporarily switches all caches to pass-through mode, replaces kernel module to new one and then restores configurations to original. Main advantage of this feature will be that exported objects (/dev/casX-Y) are available through the 
 whole process - you don't have to unmount them nor stop IO.
However upgrade in flight is still under development and not ready to use yet.

**Comment by beef9999** [comment]
@mmichal10 No data lose or corruption any more, thanks.
