### ISSUE TITLE
[Question] Under what circumstances the  `_blockdev_make_request_fast` would fail?

### ISSUE THREAD

**Issue by beef9999** [Open-CAS/open-cas-linux#366]
Then fall back to kernel IO scheduler?

**Comment by imjfckm** [comment]
Aside from error handling the most important reason for that is that the request that was created misses the cache. That's the reason fastpath exists - complete read/write requests if they hit cache without going through IO-scheduler.
You can review the implementation of this logic in [https://github.com/Open-CAS/ocf/blob/master/src/engine/engine_fast.c](url) And if you have any further questions - ask away!

**Comment by beef9999** [comment]
@imjfckm I mean why we let it fail, rather than deal it inside the CAS module.

Considering CAS has already taken over the whole disk, would it be appropriate to write the backend device by itself?

**Comment by imjfckm** [comment]
Ah, okay, I missed that part of explanation. Let me clarify.

When `_blockdev_make_request_fast` fails in `cas_cache.ko` it doesn't return directly to the kernel - instead it goes back around in `cas_disk.ko` and is resubmitted to io_queue. (see: https://github.com/Open-CAS/open-cas-linux/blob/d11f434a76816bd4889d99f6dd6aa5a293790780/modules/cas_disk/exp_obj.c#L75-L80)

The reasoning here is that if we have a cache hit we can quickly complete the I/O in submitter context, otherwise we need to "fall-back" to usual I/O path where it passes through our queues.

Does this make sense?

PS. You can choose if you want to use this behavior using `use_io_scheduler` module parameter of `cas_cache.ko`.

**Comment by beef9999** [comment]
@imjfckm I noticed there is only one write function of kernel `submit_bio` registered to `cas_object_blk_properties`, which is responsible for writing core device.
But who is there for writing SSD cache device?

**Comment by imjfckm** [comment]
`cas_object_blk_properties` is general object used for describing block devices. OCF uses those for devices of given type. Both SSD cache and HDD/SSD core are block devices, so both will use the same function to submit I/Os to drive.
