### ISSUE TITLE
Mount Core Device as Read Only for backups

### ISSUE THREAD

**Issue by darktorana** [Open-CAS/open-cas-linux#480]
### Question:
This will potentially come across as a silly question, but can you mount the code device into another folder as **read only** for the purposes of backing up.
We understand of course that the data on the core device will not be up to-date if there are writes in the cache that haven't been written back

### Reason:
We have multiple servers that are spec'd identically and have almost similar workloads and amounts of data, however the servers with Open-Cas in front of the data mounts are taking about 600% longer to backup than the ones without the cache (about 80 hours against ~14 hours).

### Example:
```
vdb        253:16   0  21.8T  0 disk
└─vdb1     253:17   0  21.8T  0 part
  └─cas1-1 252:0    0  21.8T  0 disk /data
```

In the above output, what we would want to do is mount vbd1 directly into another folder, say '/backup-readonly' and take a backup of that disk ie:
```
vdb        253:16   0  21.8T  0 disk
└─vdb1     253:17   0  21.8T  0 part /backup-readonly
  └─cas1-1 252:0    0  21.8T  0 disk /data
```

### Our concerns are:
1. Will this affect the Open CAS if we read from the core disk?
2. While the data might not be quite up to date if the cache hasn't written back, will the data still be usable on the core disk.
IE We have a file called 'customer.xml' which has one line that says 'line1', someone opens it and writes to it (changing 'line1' to 'hello' and saves it, which is done in the cache. If we were able to backup the core disk before the cache has written back, would that customer.xml file still have 'line1' written in it, or would the file just be corrupt?

**Comment by imjfckm** [comment]
Hi @darktorana, thank you for your issue.

I'm assuming here that you're using WriteBack, as you mentioned in your other issue.

### Answers
Re 1: It shouldn't affect Open CAS operation. I think it might impact the performance as you will be stressing the core device in addition to CAS normal operation.
Re 2: There is no guarantee for **any** file to say intact. Also, there is a possibility of filesystem metadata corruption. For that reason **I'd advise strongly against this solution.**

### Hypothesis explaining low performance
We've discussed your issue internally and came up with possible explanation why you're seeing such degraded performance while backing-up the device through CAS exported object.
Probably when you're backing up your whole FS sequentially a very unfortunate pattern of I/O emerges which triggers sequential cutoff which in turn triggers cleaning concurrently to you reading your data.

### Suggestions
To try and avoid such performance penalty you could try to stich cache to WO mode and disable sequential cutoff 
```bash
casadm -Q -i <cache_id> -c wo -f no
casadm -X -n seq-cutoff -i <cache_id> -p never
```
**IMPORTANT:** WO cache mode until recently manifested sporadic transient data corruption defect. Please make sure you've updated your CAS installation.

**Comment by darktorana** [comment]
Hi imjfckm, 
Thanks so much for getting back to me!

Re Re 1: I would have thought that reading through the ~10TB of data via the 1TB of cache would already be stressing it, however I could certainly be wrong.

Re Re 2: I would have happily been the guinea pig to find out if the data would stay in tact by backing up the read only partition, but the possibility of metadata corruption even in read only really concerns me. Obviously I don't understand Filesystems nearly as well as yourselves, so I'll take your word for it, but is it possible to explain why this is the case?

I certainly can't put the cache in WO mode, the majority of it's work should be read operations (it's a mail server) and putting it in WO would kill the performance boost we got from using OpenCAS in the first place!

The sequential cutoff, is it possible to use that to have it bypass caching the backup operation, or workloads like it. I had a read through the documentation but I'm still not positive how to get it to ignore the process. It is a file level backup, so it would be reading the drive sequentially but not the disk (unless the disk is unfragmented which I highly doubt).

**Comment by imjfckm** [comment]
Full disclaimer: I'm not an expert on filesystems as well, so I might under- or over-estimate the dangers.

Re 1: It probably depends on the workload on top of CAS, intensity of back-up operations and the devices involved. I think that unless something is very off with actual performance I wouldn't worry about that.

Re 2: The only corruption we're talking about here is corruption of the backups - not the actual FS being backed up (as you'd mount it RO).

The risk I see here is: OCL will cache FS metadata as it's one of the hottest I/O classes you have and will rarely flush it to core (at least with default ALRU cleaning policy). So I would imagine it's likely that the FS metadata on core is very out-of-sync with the rest of core's contents.
Example scenario I have in mind:
1. You create file in FS on CAS
2. File grows and triggers some reshuffling on the FS (compaction, remapping of some blocks)
3. The file stops being updated, data becomes cold and is flushed by ALRU to the core device
4. Metadata doesn't get flushed because it's updated continuously because of some other files being updated/created
5. Now on core you have new data, but FS metadata is still old (from 1. or even earlier) or partially old - this is the state you're backing up

You also have some more convoluted scenarios involving parts of FS metadata already flushed, and parts of it still on cache device - that would be probably even more dangerous.

I'm not sure how robust modern FS's are, but there must be a limit on what kinds of faults are recoverable and with what result, especially if data is simply not there.

I wouldn't rule-out WO. You could only switch it for the duration of taking the backup. There is a significant difference between how WO handles reads and WB handles reads. WO can glue together data read from cache and core, WB in case of partial miss will clean the data first - that's one source of cleaning activity, which can impact performance. Sequential cutoff as you said would make sense if the files weren't fragmented and cache wasn't fragmented. But unfortunately it probably will be, that means that there is possibility that sequential cut off would trigger even more background cleaning while you're backing up your data.

**Comment by darktorana** [comment]
Thanks for that thorough explanation.

I like the idea of changing to WO during the backup operation, but since the backup operation takes ~24 hours to run, and we do daily backups, it would be in WO permanently, which means no read performance increase (well, from the cache).

I fully understand now that the RO mount could mean that the backup data is corrupt, however I think I am willing to risk it during some tests, and see if it does end up going that way. I'll speak to the others here and get some feedback on what we all think is the best course of action.

I would keep this ticket open in case we do go ahead and try, we can give you some feedback. But since you have answered my questions as best as can be done with the information at hand, I understand closing it if you would like me to.

**Comment by darktorana** [comment]
We won't be able to test if RO works or not, so although it may resolve our issue, the risk is just a bit too high for us to use.

Thanks for your time with this.
