### ISSUE TITLE
Enable atomic writes

### ISSUE THREAD

**Issue by khristenkovladimir** [Open-CAS/open-cas-linux#589]
## Question

I have the same issue - https://github.com/Open-CAS/open-cas-linux/issues/415

Could you tell if atomic writes will be supported in the near future?
Do you have any tests or documentation that can show how performance increases when using atomic writes?

Maybe we can format nvme using nvme-cli, isdct, intelmas etc..?

## Motivation
Get maximum performance from cache device

## Your Environment

* OpenCAS version : 20.03.3
* Operating System: CentOS 8.2
* Kernel version: 4.18.0-193.28.1
* Cache device type (model): Intel(R) Optane(TM) P4800x SSD 350GB

**Comment by arutk** [comment]
Hi @khristenkovladimir. Unfortunately we currently don't have plans to enable back atomic writes. However we are open for collaboration and willing to support contributors from outside Intel to enable this.

Atomic mode is not supported for so long that we don't have any perf data or tests to share with you. Performance gains in current design were mixed, since the gains from reducing number of I/O were often offset by additional CPU overhead (memcopy for each I/O to interleave metadata and data) and additional I/O to clear metadata before eviction. Memcopy overhead would probably be avoidable if used with hardware support for separate metadata buffer (rather than interleaved with data). 

Other potential challenges:
1.  Formatting the device - like you mentioned this can be achieved using another tool. 
2.  Checking device format - this was also done using ioctl from inside CAS driver. From security standpoint we would probably prefer to to have this check done in kernel rather than depending on userspace to do it right.
3. Sending I/O with metadata to NVME driver - I'm not up to date with current state of kernel interfaces for this purpose.

**Comment by khristenkovladimir** [comment]
Hi @arutk.

Thank you for the information and for sharing the current state of the issue.
