### ISSUE TITLE
OpenCAS splits writes while flushing dirty data back to core device？

### ISSUE THREAD

**Issue by jimmygc** [Open-CAS/open-cas-linux#619]
## Question
I've been testing OpenCAS with wb policy this few weeks, and I found that it splits the original write into small writes in cache line size when flushing dirty data back to core device.  For example, it will generate lots of 4K write request to core device after I write one single 1MB block, which cause even more io pressure on core device than the original one.
I know there is a option call seq_cutoff, but this will only work in the situation of large sequential writes. There is still a performance issue, when facing large mount of random IO which larger than cache line. For example, a lot of 64K random io will generate 16X amount of io when using 4K cache line.
Is there any other tuning option to prevent OpenCAS from spliting io or even make it merge sequential small writes?

## Motivation
I am using OpenCAS as a cache for kernel RBD device. As I know,  the performance of sequential small IO on ceph RBD device is considerably slow. In addition, a lot of small io will have a greate impact on overall performance of a ceph cluster.

## Your Environment

* OpenCAS version (commit hash or tag): 20.03.02.00001110
* Operating System:  CentOS 7
* Kernel version: 4.4.52
* Cache device type (model):  INTEL SSDPE21K750GA
* Core device type (model): KRBD device running on a cluster of 9 osd (INTEL SSDPE2KX010T8)
* Cache configuration:
* * Cache mode: wb
* * Cache line size: 4K
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)

**Comment by robertbaldyga** [comment]
OpenCAS operates on cache lines and it does not track information about original requests, so flushing data with request granularity is not possible. OpenCAS tries to merge cleaned cache lines into bigger requests, however cache lines to clean are chosen in ALRU fashion, so there is high probability that most of the flushing will be done with cache line granularity. I think the simplest way to improve the situation would be to select bigger cache line size.

Sequential cutoff brings the benefit in the situations when sequentially written data is cold data, because requests filtered by sequential cutoff bypass the cache, so if you have huge requests carrying hot data, sequential cutoff set to too low threshold may decrease the hit ratio.

The another thing is that having a lot of cleaning during io workload (which is result of intensive eviction) may indicate too low hit ratio, which can be improved by increasing the cache capacity.

**Comment by jimmygc** [comment]
OK, maybe OpenCAS just not suitable to use as a cache for slow core device,  which performs poorly under random and sequential small io.
I am using bcache as well, it merges sequential small io into one big io when flushing back into backing device. This is why I ask if OpenCAS can provide a similar capability.

**Comment by imjfckm** [comment]
to add to what @robertbaldyga said - you could also try switching cleaning policy to ACP. This way CAS will try to flush without regard for hotness and in sorted order. Afterwards the kernel block layer or RBD driver itself should be able to merge those IOs if they are sequential.

**Comment by imjfckm** [comment]
@jimmygc , please let us know if you tested this solution and if it helped.

**Comment by jimmygc** [comment]
@imjfckm I tested with ACP policy, but the sequential small writes are still no merged. From ceph client statistics info, the IOs is still small and separated. I think OpenCAS may write into core device with O_DIRECT flag, which disables the kernel block layer's cache and its io merge functionality，maybe for tolerance of power outage. In addition, I think Kernal RBD driver itself never merge any sequential small IOs.
