### ISSUE TITLE
CAS with NOP cleaning policy cleans some data on soft system restart

### ISSUE THREAD

**Issue by Deixx** [Open-CAS/open-cas-linux#769]
## Description

After reboot dirty data drops and clean data increases when it should not. Test uses Write-Back with NOP cleaning policy and different configurations of cache line size and kernel parameters. After IO the test reboots platform and then loads cache and checks statistics.

## Expected Behavior

Dirty/Clean data stays the same.

## Actual Behavior

Some data (usually 1 or 2 cache lines - max 4 for 4KiB cache line size) are cleaned between reading stats before and after reboot.

## Steps to Reproduce

Reproduction rate ~40%.
1. Create xfs on core device.
2. Create a file on the core device.
3. Start a cache in Write-Back mode, set cleaning policy to NOP and add the core device. 
4. Create another file on the exported object.
5. Flush cache data.
6. Read the file created in step 2 from the exported object and create another file. (Now files 1 and 3 are in cache).
7. Read statistics.
8. Reboot.
9. Load cache and read statistics.

## Logs

Example stats before and after reboot:
```
Cache Id                  1
Cache Size                516192 [4KiB Blocks] / 1.97 [GiB]
Cache Device              /dev/nvme0n1p1
Core Devices              1
Inactive Core Devices     0
Write Policy              wb
Eviction Policy           lru
Cleaning Policy           nop
Promotion Policy          always
Cache line size           8 [KiB]
Metadata Memory Footprint 31.9 [MiB]
Dirty for                 3 [s] / 3 [s]
Metadata Mode             normal
Status                    Running

+==================+========+======+=============+
| Usage statistics | Count  |  %   |   Units     |
+==================+========+======+=============+
| Occupancy        | 230574 | 44.7 | 4KiB Blocks |
| Free             | 285618 | 55.3 | 4KiB Blocks |
| Clean            | 153770 | 29.8 | 4KiB Blocks |
| Dirty            |  76804 | 14.9 | 4KiB Blocks |
+==================+========+======+=============+
```
```
+==================+========+======+=============+
| Usage statistics | Count  |  %   |   Units     |
+==================+========+======+=============+
| Occupancy        | 230574 | 44.7 | 4KiB Blocks |
| Free             | 285618 | 55.3 | 4KiB Blocks |
| Clean            | 153774 | 29.8 | 4KiB Blocks |
| Dirty            |  76800 | 14.9 | 4KiB Blocks |
+==================+========+======+=============+
```

## Your Environment

* OpenCAS version (commit hash or tag): 21.03.0.0474.master, 21.03.0.0477.master
* Operating System: RHEL 8.3
* Kernel version: 4.18.0-240.el8.x86_64
* Cache device type (NAND/Optane/other): Optane
* Cache configuration:
* * Cache mode: WB
* * Cache line size: different sizes
* * Promotion policy: always
* * Cleaning policy: NOP

**Comment by jfckm** [comment]
What is happening here is:
1. <test is inserting some dirty data into cache>
2. Cache statistics are gathered for comparison
3. Test triggers reboot
4. lvm2-monitor service is stopped and triggers rescan of all block devices (`lvm vgchange --monitor n`)
5. This rescan is reading data from cache and is touching partially dirty data
6. CAS flushes dirty data because of partially dirty read
7. Reboot
8. Load cache
9. Get cache statistics

The reason why dirty stats in 2 and 9 are different is LVM rescan in 4. To avoid this you could either disable/mask `lvm2-monitor.service`. Unfortunately this is not a very robust solution and on other distros/configs it could need some further work to make sure no one reads from cache after collecting stats.
