### ISSUE TITLE
Multi-level cache at boot

### ISSUE THREAD

**Issue by alxtrl** [Open-CAS/open-cas-linux#785]
## Question
I'm trying to setup a multi-level cache using a SSD and a ramdisk, but the ramdisk seems to be not ready when open-cas service starts.
I made the following steps:

**ramdisk setup**

in /etc/modules-load.d/ramdisk.conf, just:
_brd_

then in /etc/modprobe.d/ramdisk.conf
_options brd rd_nr=1 rd_size=67108864 max_part=1_

**To create a link in /dev/disk/by-id**

in /etc/udev/rules.d/59-ramdisk-device-by-id.rules

_# RAMDISK
KERNEL=="ram*[0-9]", SUBSYSTEM=="block", SYMLINK+="disk/by-id/ramdisk%n"_

How can I control the correct timing?

Thank you.
Alessandro

## Your Environment

* OpenCAS version (commit hash or tag): 20.12.2.0444
* Operating System: Oracle Linux 8.3
* Kernel version: 4.18.0-240.15.1
* Cache device type (NAND/Optane/other): Optane & RAM
* Core device type (HDD/SSD/other): RAID Array
* Cache configuration: Multi-level
* * Cache mode: (default: wt) WT
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

**Comment by robertbaldyga** [comment]
Hi @alxtrl,

We are looking at your issue. We will let you know once we find a solution.

**Comment by robertbaldyga** [comment]
Hi @alxtrl 

Currently we do not support this configuration.

During startup we require that all devices to contain valid Open CAS metadata. This requirement cannot be fulfilled by ramdisk. Because of that with current Open CAS version you cannot have configuration with ramdisk as a cache that automatically loads after reboot.

The only workaround I'm able to propose right now is to recreate cache configuration in init script using casadm commands.

I will add feature request for that missing functionality in separate GitHub issue.

Regards,
Robert

**Comment by robertbaldyga** [comment]
Hi @alxtrl,

I created feature request to support your configuration:
https://github.com/Open-CAS/open-cas-linux/issues/792

I'll let you know once we determine the ETA.

Regards,
Robert

**Comment by alxtrl** [comment]
Thank you!

Ciao,
AT

------------------------------------------------------------------------
*Alessandro Tirel
Servizio Calcolo e Reti*
INFN - Sezione di Trieste
Loc. Padriciano, 99
c/o Area di Ricerca - Pal. L3
34149 Trieste - Italy
tel. +39 (040) 3756257
fax +39 (040) 3756258
